name: ui
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+4

environment:
  sdk: ^3.1.0

dependencies:
  common_dependencies:
    path: ../../modules/common_dependencies

  common_ui:
    path: ./common_ui
  state_management:
    path: ../../modules/state_management
