name: presentation
description: a project that demonstrates the bloc pattern in flutter using the Bloc package
publish_to: 'none'
version: 1.1.0+4

scripts:
  create:
    module: dart create -t package

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # COMMON
  common_dependencies:
    path: ./modules/common_dependencies

  state_management:
    path: ./modules/state_management

  # UI
  ui:
    path: ./modules/ui
  common_ui:
    path: ./modules/ui/common_ui


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true